# To run use conda env create -f environment.yml
name: uw_alerts_env_3_10
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyproj=3.4.1
  - folium=0.14.0
  - shapely=2.0.1
  - flask=2.2.2
  - numpy=1.24.2
  - pylint=2.16.2
  - geopandas=0.12.2
  - openai=0.26.5
  - transformers=4.26.1
  - pip
  - pip:
    - -r requirements.txt
  - requests=2.28.1
  - bs4=4.11.1
  - python-dotenv=0.21.0
  - pandas=1.5.2
